# Copyright (c) 2026 Sławomir Laskowski
# https://github.com/sshlio/dot
# Licensed under the MIT License. See LICENSE file for details.

hide_window_decorations titlebar-only
cursor_trail 0
shell /Users/billy/bin/shell
input_delay 0
background #333333
repaint_delay 0
sync_to_monitor no
wayland_enable_ime no
copy_on_select yes

font_family Hack Nerd Font
bold_font Hack Nerd Font
font_size 15.0

cursor_blink_interval 0
cursor_stop_blinking_after 0.0
mouse_hide_wait	-3.0

### KEYBINDINGS

map cmd+w
map cmd+r
map cmd+v
map cmd+i
map cmd+i
map cmd+n

map cmd+b goto_tab -1
map cmd+shift+w close_tab

### TABS

tab_bar_min_tabs 0
tab_bar_style powerline
tab_bar_style slant
tab_title_template  "{title} [{index}]"

map cmd+shift+w close_tab
map cmd+shift+1 goto_tab 1
map cmd+shift+2 goto_tab 2
map cmd+shift+3 goto_tab 3
map cmd+shift+4 goto_tab 4
map cmd+shift+5 goto_tab 5
map cmd+shift+6 goto_tab 6
map cmd+shift+7 goto_tab 7
map cmd+shift+8 goto_tab 8
map cmd+shift+9 goto_tab 9

map f1 launch --type=overlay-main --title "bmenu" --spacing margin=20 --hold --dont-take-focus=yes nu -c "ls | fzf --min-height=20 --margin=10,2 --layout=reverse"
