# Copyright (c) 2026 Sławomir Laskowski
# https://github.com/sshlio/dot
# Licensed under the MIT License. See LICENSE file for details.

shell /Users/billy/bin/shell
hide_window_decorations titlebar-only

input_delay 0
cursor_trail 0
background #333333
repaint_delay 0
sync_to_monitor no
wayland_enable_ime no
copy_on_select yes
font_size 18.0

cursor_blink_interval 0
cursor_stop_blinking_after 0.0
mouse_hide_wait	-3.0

confirm_os_window_close 0

### KEYBINDINGS

map cmd+w
map cmd+r
map cmd+v
map cmd+i
map cmd+i
map cmd+n
map cmd+f
map § send_key `
map shift+§ send_key ~

map cmd+b goto_tab -1
map cmd+shift+w close_tab

### TABS

tab_bar_min_tabs 0
tab_bar_style powerline
tab_title_template "{title}{sup.index}"

map cmd+shift+w close_tab
map cmd+shift+1 goto_tab 1
map cmd+shift+2 goto_tab 2
map cmd+shift+3 goto_tab 3
map cmd+shift+4 goto_tab 4
map cmd+shift+5 goto_tab 5
map cmd+shift+6 goto_tab 6
map cmd+shift+7 goto_tab 7
map cmd+shift+8 goto_tab 8
map cmd+shift+9 goto_tab 9
map cmd+shift+0 goto_tab 10

bold_font        auto
italic_font      auto
bold_italic_font auto

font_family family="Monaspace Neon" features="+calt +liga +ss01 +ss02 +ss03 +ss04 +ss05 +ss06 +ss07 +ss08"
disable_ligatures never
