---

- hosts: all
  tasks:
    - name: Install brew packages
      homebrew:
        name:
         - nushell
         - rg
         - neovim
         - git-delta
        state: present

    - name: Configure git to use delta as pager
      git_config:
        name: core.pager
        value: delta
        scope: global

    - name: Delta side by side
      git_config:
        name: delta.side-by-side
        value: "true"
        scope: global

    - name: Ensure config files exist
      file:
        path: "{{ item }}"
        state: touch
        mode: '0600'
      loop:
        - "~/.npmrc"
        - "~/.config/nvim/init.local.lua"
        - "~/.config/nushell/config.local.nu"
    - name: Ensure ~/bin exists

      file:
        path: "~/bin"
        state: directory

    - name: Link vimrc
      ansible.builtin.import_tasks: tasks/symlink/main.yaml
      vars:
        symlink_src: "{{ playbook_dir }}/../.vimrc"
        symlink_dest: "{{ ansible_facts['env']['HOME'] }}/.vimrc"

    - name: Npmrc config
      lineinfile:
        path: ~/.npmrc
        regexp: '^{{ item.key }}\s*='
        line: '{{ item.key }}={{ item.value }}'
        state: present
      loop:
        - { key: 'min-release-age', value: '3' }
        - { key: 'ignore-scripts', value: 'true' }

    # Inherit PATH env from zsh
    - name: Zsh nushell wrapping
      ansible.builtin.copy:
        dest: ~/bin/shell
        mode: '0555'
        content: |
          #!/bin/zsh -l
          exec nu

    # use `defaults find NSUserKeyEquivalents` to debug
    - name: Set Chrome shortcuts
      community.general.osx_defaults:
        domain: com.google.Chrome
        key: NSUserKeyEquivalents
        type: dict
        value:
          "Save Page As...": "@$s"
