set hidden_filter ^\.|\.(?:pyc|pyo|bak|swp)$|^lost\+found$|^__(py)?cache__$|^node_modules|_billy$
# Keep Ranger's standard hidden-file rules and also hide dependency trees.
default_linemode devicons
set colorscheme dot
set confirm_on_delete never

map H set show_hidden!
map os chain setlocal sort size;  move to=0
map om chain setlocal sort mtime; move to=0
map dd delete
map cr bulkrename
map rv shell -f open -R %f
map i edit
map ] tab_move 1
map [ tab_move -1
map ;<any> enter_bookmark %any
map / console find%space
map <Space> shell -c qlmanage -p %p

set collapse_preview false

setlocal path=~/Downloads sort_directories_first false
setlocal path=/tmp sort_directories_first false
setlocal path=~/Downloads sort mtime
